#!/usr/bin/env python3
"""
Script to create a CODEOWNERS file in a GitHub repository.

Uses the GitHub REST API to create a file via:
  PUT /repos/{owner}/{repo}/contents/{path}

Usage:
  python3 scripts/create_codeowners.py \
    --org "my-org" \
    --repo "my-repo" \
    --rules "* @platform-team\n/src/ @dev-team" \
    --token "ghp_xxx"
"""

import argparse
import base64
import json
import sys
import urllib.request
import urllib.error


API_BASE = "https://api.github.com"


def api_request(url: str, token: str, method: str = "GET", data: dict = None) -> dict:
    """Make a GitHub API request."""
    payload = json.dumps(data).encode() if data else None
    req = urllib.request.Request(url, data=payload, method=method)
    req.add_header("Authorization", f"Bearer {token}")
    req.add_header("Accept", "application/vnd.github+json")
    req.add_header("X-GitHub-Api-Version", "2022-11-28")
    if data:
        req.add_header("Content-Type", "application/json")

    try:
        with urllib.request.urlopen(req) as response:
            body = response.read().decode()
            return {"success": True, "status": response.status, "data": json.loads(body) if body else {}}
    except urllib.error.HTTPError as e:
        body = e.read().decode()
        try:
            error_data = json.loads(body)
        except json.JSONDecodeError:
            error_data = {"message": body}
        return {"success": False, "status": e.code, "data": error_data}


def parse_codeowners_rules(rules_str: str) -> str:
    """Parse and validate CODEOWNERS rules."""
    if not rules_str or rules_str.strip() == "" or rules_str.strip() == "_No response_":
        return ""

    lines = rules_str.strip().split("\n")
    validated_lines = []
    header = [
        "# CODEOWNERS file — auto-generated by GitHub Admin Workflow",
        "# https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/about-code-owners",
        "#",
        "# Each line is a file pattern followed by one or more owners.",
        "# Order matters — last matching pattern takes priority.",
        "",
    ]
    validated_lines.extend(header)

    for line in lines:
        line = line.strip()

        # Keep comments and empty lines
        if not line or line.startswith("#"):
            validated_lines.append(line)
            continue

        parts = line.split()
        if len(parts) < 2:
            print(f"WARNING: Skipping invalid CODEOWNERS rule (no owner specified): '{line}'")
            continue

        pattern = parts[0]
        owners = parts[1:]

        # Validate owners format (@user, @org/team, or email)
        valid_owners = []
        for owner in owners:
            if owner.startswith("@") or "@" in owner:
                valid_owners.append(owner)
            else:
                print(f"WARNING: Invalid owner format '{owner}' in rule '{line}'. Prefixing with @.")
                valid_owners.append(f"@{owner}")

        if valid_owners:
            validated_lines.append(f"{pattern} {' '.join(valid_owners)}")

    return "\n".join(validated_lines) + "\n"


def check_file_exists(org: str, repo: str, path: str, token: str) -> dict:
    """Check if a file already exists in the repo."""
    result = api_request(f"{API_BASE}/repos/{org}/{repo}/contents/{path}", token)
    if result["success"]:
        return {"exists": True, "sha": result["data"].get("sha", "")}
    return {"exists": False, "sha": ""}


def create_codeowners_file(org: str, repo: str, content: str, token: str, sha: str = None) -> dict:
    """Create or update the CODEOWNERS file in the repository."""

    # GitHub supports CODEOWNERS in root, docs/, or .github/
    # Using .github/CODEOWNERS as best practice
    path = ".github/CODEOWNERS"

    encoded_content = base64.b64encode(content.encode()).decode()

    data = {
        "message": "Add CODEOWNERS file — auto-generated by admin workflow",
        "content": encoded_content,
    }

    if sha:
        data["message"] = "Update CODEOWNERS file — auto-generated by admin workflow"
        data["sha"] = sha

    result = api_request(
        f"{API_BASE}/repos/{org}/{repo}/contents/{path}",
        token,
        method="PUT",
        data=data,
    )

    return result


def main():
    parser = argparse.ArgumentParser(description="Create CODEOWNERS file in a GitHub repository")
    parser.add_argument("--org", required=True, help="GitHub organization")
    parser.add_argument("--repo", required=True, help="Repository name")
    parser.add_argument("--rules", required=True, help="CODEOWNERS rules (newline-separated)")
    parser.add_argument("--token", required=True, help="GitHub PAT with repo scope")
    args = parser.parse_args()

    org = args.org.strip()
    repo = args.repo.strip()

    print(f"{'=' * 60}")
    print(f"CODEOWNERS File Management")
    print(f"{'=' * 60}")
    print(f"Organization: {org}")
    print(f"Repository:   {repo}")
    print(f"{'=' * 60}")

    # Step 1: Parse and validate rules
    print("\n📋 Parsing CODEOWNERS rules...")
    content = parse_codeowners_rules(args.rules)

    if not content.strip():
        print("ERROR: No valid CODEOWNERS rules provided.")
        sys.exit(1)

    print("\n📄 Generated CODEOWNERS file:")
    print("-" * 40)
    print(content)
    print("-" * 40)

    # Step 2: Check if CODEOWNERS already exists
    print("\n📋 Checking for existing CODEOWNERS file...")
    existing = check_file_exists(org, repo, ".github/CODEOWNERS", args.token)

    if existing["exists"]:
        print("   ⚠️  CODEOWNERS file already exists. Will update it.")
        sha = existing["sha"]
    else:
        print("   ✅ No existing CODEOWNERS file found. Will create new.")
        sha = None

    # Step 3: Create/Update CODEOWNERS
    action = "Updating" if sha else "Creating"
    print(f"\n🚀 {action} .github/CODEOWNERS...")

    result = create_codeowners_file(org, repo, content, args.token, sha)

    if result["success"]:
        file_url = result["data"].get("content", {}).get("html_url", "N/A")
        commit_sha = result["data"].get("commit", {}).get("sha", "N/A")[:7]
        print(f"\n✅ CODEOWNERS file {action.lower().replace('ing', 'ed')} successfully!")
        print(f"   URL:    {file_url}")
        print(f"   Commit: {commit_sha}")
    else:
        error_msg = result["data"].get("message", "Unknown error")
        print(f"\n❌ Failed to create CODEOWNERS file!")
        print(f"   Error: {error_msg}")
        sys.exit(1)


if __name__ == "__main__":
    main()
