name: New Repository Request
description: Request creation of a new GitHub repository with access granted to existing teams
title: "[REPO REQUEST] "
labels: ["repo-request", "pending-review"]
assignees:
  - devsecops-team

body:
  - type: markdown
    attributes:
      value: |
        ## Repository Request Form
        Please fill out this form to request a new repository. Your request will be reviewed by the DevSecOps team.

        **Note:** The repository will be created with:
        - Access granted to existing teams you specify
        - Default settings based on existing repository configurations

        **Default Configuration:**
        All settings not specified in this form (visibility, features, security, topics, etc.) will use default values from existing repository configurations in the organization.

  - type: input
    id: repo-name
    attributes:
      label: Repository Name
      description: Name of the new repository (lowercase, hyphens only, no spaces)
      placeholder: "mbb-new-service"
    validations:
      required: true

  - type: input
    id: teams
    attributes:
      label: Team Access
      description: Comma-separated list of existing team slugs that should have access to this repository. Teams must already exist in the organization. (Team existence will be validated)
      placeholder: "platform-team, backend-developers, qa-team"
    validations:
      required: true

  - type: dropdown
    id: tech-stack
    attributes:
      label: Tech Stack
      description: Primary technology stack for this repository
      options:
        - React
        - Java Springboot
        - NodeJS
        - Python
        - Others (specify below)
    validations:
      required: true

  - type: input
    id: tech-stack-other
    attributes:
      label: Other Tech Stack
      description: If you selected "Others", please specify the tech stack
      placeholder: "e.g., Ruby on Rails, Go, .NET"

  - type: textarea
    id: justification
    attributes:
      label: Business Justification
      description: Explain why this repository is needed and how it will be used
      placeholder: |
        - Business need:
        - Expected usage:
        - Impact:
    validations:
      required: true

  - type: dropdown
    id: default-branch
    attributes:
      label: Default Branch Name
      options:
        - main
        - master
        - develop
      default: 0
    validations:
      required: true

  - type: checkboxes
    id: terms
    attributes:
      label: Acknowledgment
      description: Please confirm you understand the following
      options:
        - label: I understand that this repository will be created with access granted to the teams I specified
          required: true
        - label: I understand that the teams I specify must already exist in the organization
          required: true
        - label: I understand that repository settings will use organization defaults unless otherwise specified
          required: true
