name: New Repository Request
description: Request creation of a new GitHub repository with automated team setup
title: "[REPO REQUEST] "
labels: ["repo-request", "pending-review"]
assignees:
  - devsecops-team

body:
  - type: markdown
    attributes:
      value: |
        ## Repository Request Form
        Please fill out this form to request a new repository. Your request will be reviewed by the DevSecOps team.

        **Note:** The repository will be created with 3 teams:
        - `{repo-name}-dev` - Developer write access
        - `{repo-name}-test` - Test manager write access
        - `{repo-name}-prod` - Production manager maintain access

        **Team Maintainers:** The admins you specify will become team maintainers with the ability to manage team membership. If no admins are specified, you (the issue creator) will become the team maintainer.

  - type: input
    id: repo-name
    attributes:
      label: Repository Name
      description: Name of the new repository (lowercase, hyphens only, no spaces)
      placeholder: "mbb-new-service"
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Repository Description
      description: Brief description of the repository purpose and what it will contain
      placeholder: "This repository will contain..."
    validations:
      required: true

  - type: dropdown
    id: tech-stack
    attributes:
      label: Tech Stack
      description: Primary technology stack for this repository
      options:
        - React
        - Java Springboot
        - NodeJS
        - Python
        - Others (specify below)
    validations:
      required: true

  - type: input
    id: tech-stack-other
    attributes:
      label: Other Tech Stack
      description: If you selected "Others", please specify the tech stack
      placeholder: "e.g., Ruby on Rails, Go, .NET"

  - type: textarea
    id: justification
    attributes:
      label: Business Justification
      description: Explain why this repository is needed and how it will be used
      placeholder: |
        - Business need:
        - Expected usage:
        - Impact:
    validations:
      required: true

  - type: input
    id: admins
    attributes:
      label: Team Maintainers
      description: Comma-separated GitHub usernames who will become team maintainers (can manage team membership). Leave empty to make yourself the maintainer. (Usernames will be validated)
      placeholder: "john-doe, jane-smith, bob-jones"
    validations:
      required: false

  - type: dropdown
    id: visibility
    attributes:
      label: Repository Visibility
      options:
        - private
        - internal
        - public
      default: 0
    validations:
      required: true

  - type: dropdown
    id: environment
    attributes:
      label: Target Environment
      description: Which environment should this repository be created in
      options:
        - dev
        - staging
        - production
      default: 0
    validations:
      required: true

  - type: checkboxes
    id: features
    attributes:
      label: Repository Features
      description: Select the features you want enabled
      options:
        - label: Enable Issues
          required: false
        - label: Enable Projects
          required: false
        - label: Enable Wiki
          required: false

  - type: checkboxes
    id: security
    attributes:
      label: Security Features
      description: Select security features (GHAS features require license)
      options:
        - label: Enable Vulnerability Alerts
          required: false
        - label: Enable Dependabot Alerts
          required: false
        - label: Enable Dependabot Security Updates
          required: false
        - label: Enable Advanced Security (GHAS)
          required: false
        - label: Enable Secret Scanning
          required: false
        - label: Enable Secret Scanning Push Protection
          required: false

  - type: input
    id: topics
    attributes:
      label: Repository Topics
      description: Comma-separated list of topics/tags for the repository
      placeholder: "backend, api, microservices, nodejs"

  - type: dropdown
    id: default-branch
    attributes:
      label: Default Branch Name
      options:
        - main
        - master
        - develop
      default: 0
    validations:
      required: true

  - type: textarea
    id: branch-protection
    attributes:
      label: Branch Protection Requirements (Optional)
      description: Specify branch protection rules if different from defaults
      placeholder: |
        Required approving reviews: 2
        Require code owner reviews: yes
        Dismiss stale reviews: no
        Require signed commits: no

  - type: textarea
    id: additional-notes
    attributes:
      label: Additional Notes
      description: Any additional information or special requirements
      placeholder: "Please add any special configuration needs or notes here..."

  - type: checkboxes
    id: terms
    attributes:
      label: Acknowledgment
      description: Please confirm you understand the following
      options:
        - label: I understand that this repository will be created with 3 default teams (dev, test, prod)
          required: true
        - label: I understand that team maintainers manage team membership and can add/remove members
          required: true
        - label: I have verified the usernames of team maintainers (if specified)
          required: true
